[[exercises]]
name = "cap-9-1"
path = "exercises/Cap.9/composite-literal-and-range.go"
mode = "compile"
hint = """
- Usando uma literal composta:
     - Crie um array que suporte 5 valores to tipo int
     - Atribua valores aos seus índices
- Utilize range e demonstre os valores do array.
- Utilizando format printing, demonstre o tipo do array."""

[[exercises]]
name = "cap-9-2"
path = "exercises/Cap.9/composite-literal-and-range-2.go"
mode = "compile"
hint = """
- Usando uma literal composta:
    - Crie uma slice de tipo int
    - Atribua 10 valores a ela
- Utilize range para demonstrar todos estes valores.
- E utilize format printing para demonstrar seu tipo."""

[[exercises]]
name = "cap-9-3"
path = "exercises/Cap.9/slicing-printing-and-len.go"
mode = "compile"
hint = """
- Utilizando como base o exercício anterior, utilize slicing para demonstrar os valores:
    - Do primeiro ao terceiro item do slice (incluindo o terceiro item!)
    - Do quinto ao último item do slice (incluindo o último item!)
    - Do segundo ao sétimo item do slice (incluindo o sétimo item!)
    - Do terceiro ao penúltimo item do slice (incluindo o penúltimo item!)
    - Desafio: obtenha o mesmo resultado acima utilizando a função len() para determinar o penúltimo item"""

[[exercises]]
name = "cap-9-4"
path = "exercises/Cap.9/append-and-printing.go"
mode = "compile"
hint = """
- Começando com a seguinte slice:
    - x := []int{42, 43, 44, 45, 46, 47, 48, 49, 50, 51}
- Anexe a ela o valor 52;
- Anexe a ela os valores 53, 54 e 55 utilizando uma única declaração;
- Demonstre a slice;
- Anexe a ela a seguinte slice:
    - y := []int{56, 57, 58, 59, 60}
- Demonstre a slice x."""

[[exercises]]
name = "cap-9-5"
path = "exercises/Cap.9/slicing-and-append.go"
mode = "compile"
hint = """
- Comece com essa slice:
    - x := []int{42, 43, 44, 45, 46, 47, 48, 49, 50, 51}
- Utilizando slicing e append, crie uma slice y que contenha os valores:
    - [42, 43, 44, 48, 49, 50, 51]"""

[[exercises]]
name = "cap-9-6"
path = "exercises/Cap.9/make-len-cap-range.go"
mode = "compile"
hint = """
- Crie uma slice usando make que possa conter todos os estados do Brasil.
    - Os estados: "Acre", "Alagoas", "Amapá", "Amazonas", "Bahia", "Ceará", "Espírito Santo",
    "Goiás", "Maranhão", "Mato Grosso", "Mato Grosso do Sul", "Minas Gerais", "Pará", "Paraíba", "Paraná",
    "Pernambuco", "Piauí", "Rio de Janeiro", "Rio Grande do Norte", "Rio Grande do Sul", "Rondônia",
    "Roraima", "Santa Catarina", "São Paulo", "Sergipe", "Tocantins"
- Demonstre o len e cap da slice.
- Demonstre todos os valores da slice *sem utilizar range.*"""

[[exercises]]
name = "cap-9-7"
path = "exercises/Cap.9/multi-dimensions.go"
mode = "compile"
hint = """
- Crie uma slice contendo slices de strings ([][]string). Atribua valores a este slice multi-dimensional da seguinte maneira:
    - "Nome", "Sobrenome", "Hobby favorito"
- Inclua dados para 3 pessoas, e utilize range para demonstrar estes dados."""

[[exercises]]
name = "cap-9-8"
path = "exercises/Cap.9/map-strings-arrays.go"
mode = "compile"
hint = """
- Crie um map com key tipo string e value tipo []string.
    - Key deve conter nomes no formato sobrenome_nome
    - Value deve conter os hobbies favoritos da pessoa
- Demonstre todos esses valores e seus índices."""

[[exercises]]
name = "cap-9-9"
path = "exercises/Cap.9/append-to-map-and-range.go"
mode = "compile"
hint = """
- Utilizando o exercício anterior, adicione uma entrada ao map e demonstre o map inteiro utilizando range."""

[[exercises]]
name = "cap-9-10"
path = "exercises/Cap.9/delete-from-map-and-range.go"
mode = "compile"
hint = """
- Utilizando o exercício anterior, remova uma entrada do map e demonstre o map inteiro utilizando range."""

[[modules]]
name = "cap-8-slice-1"
path = "modules/Cap.8/Slices/slice-1.go"
mode = "compile"
hint = """
Literal composta"""

[[modules]]
name = "cap-8-slice-2"
path = "modules/Cap.8/Slices/slice-2.go"
mode = "compile"
hint = """
For range"""

[[modules]]
name = "cap-8-slice-3"
path = "modules/Cap.8/Slices/slice-3.go"
mode = "compile"
hint = """
For literal"""

[[modules]]
name = "cap-8-slice-4"
path = "modules/Cap.8/Slices/slice-4.go"
mode = "compile"
hint = """
Deletando itens da slice (fatiando)"""

[[modules]]
name = "cap-8-slice-5"
path = "modules/Cap.8/Slices/slice-5.go"
mode = "compile"
hint = """
Anexando (juntando) slices"""

[[modules]]
name = "cap-8-slice-6"
path = "modules/Cap.8/Slices/slice-6.go"
mode = "compile"
hint = """
Criando uma slice com make"""

[[modules]]
name = "cap-8-slice-7"
path = "modules/Cap.8/Slices/slice-7.go"
mode = "compile"
hint = """
Slice multi dimensionais"""

[[modules]]
name = "cap-8-slice-8"
path = "modules/Cap.8/Slices/slice-8.go"
mode = "compile"
hint = """
A surpresa do array subjacente"""

[[modules]]
name = "cap-8-maps"
path = "modules/Cap.8/Maps/maps.go"
mode = "compile"
hint = """
Introdução aos maps"""

[[modules]]
name = "cap-8-maps-range"
path = "modules/Cap.8/Maps/maps-range.go"
mode = "compile"
hint = """
For range e deletando"""

[[modules]]
name = "cap-10-struct-1"
path = "modules/Cap.10/Struct/1.go"
mode = "compile"
hint = """
HINT HERE"""

[[modules]]
name = "cap-10-struct-2"
path = "modules/Cap.10/Struct/2.go"
mode = "compile"
hint = """
HINT HERE"""

[[modules]]
name = "cap-10-struct-3"
path = "modules/Cap.10/Struct/3.go"
mode = "compile"
hint = """
HINT HERE"""

[[modules]]
name = "cap-10-struct-4"
path = "modules/Cap.10/Struct/4.go"
mode = "compile"
hint = """
HINT HERE"""

[[modules]]
name = "cap-12-functions-1"
path = "modules/Cap.12/Functions/1.go"
mode = "compile"
hint = """
HINT HERE"""

[[modules]]
name = "cap-12-functions-2"
path = "modules/Cap.12/Functions/2.go"
mode = "compile"
hint = """
HINT HERE"""

[[modules]]
name = "cap-12-functions-3"
path = "modules/Cap.12/Functions/3.go"
mode = "compile"
hint = """
HINT HERE"""

[[modules]]
name = "cap-12-functions-4"
path = "modules/Cap.12/Functions/4.go"
mode = "compile"
hint = """
HINT HERE"""

[[modules]]
name = "cap-12-functions-5"
path = "modules/Cap.12/Functions/5.go"
mode = "compile"
hint = """
HINT HERE"""

[[modules]]
name = "cap-12-functions-5-1"
path = "modules/Cap.12/Functions/5.1.go"
mode = "compile"
hint = """
HINT HERE"""

[[modules]]
name = "cap-12-functions-6"
path = "modules/Cap.12/Functions/6.go"
mode = "compile"
hint = """
HINT HERE"""

[[modules]]
name = "cap-12-functions-7"
path = "modules/Cap.12/Functions/7.go"
mode = "compile"
hint = """
HINT HERE"""

[[modules]]
name = "cap-12-functions-8"
path = "modules/Cap.12/Functions/8.go"
mode = "compile"
hint = """
HINT HERE"""

[[modules]]
name = "cap-12-functions-9"
path = "modules/Cap.12/Functions/9.go"
mode = "compile"
hint = """
HINT HERE"""

[[modules]]
name = "cap-12-functions-10"
path = "modules/Cap.12/Functions/10.go"
mode = "compile"
hint = """
HINT HERE"""

[[modules]]
name = "cap-12-functions-11"
path = "modules/Cap.12/Functions/11.go"
mode = "compile"
hint = """
HINT HERE"""

[[modules]]
name = "cap-12-functions-11-1"
path = "modules/Cap.12/Functions/11.1.go"
mode = "compile"
hint = """
HINT HERE"""

[[modules]]
name = "cap-12-functions-exercise-1"
path = "modules/Cap.12/Functions/exercise.1.go"
mode = "compile"
hint = """
HINT HERE"""

[[modules]]
name = "cap-14-pointers-1"
path = "modules/Cap.14/Pointers/1.go"
mode = "compile"
hint = """
HINT HERE"""

[[modules]]
name = "cap-14-pointers-2"
path = "modules/Cap.14/Pointers/2.go"
mode = "compile"
hint = """
HINT HERE"""

[[modules]]
name = "cap-16-applications-bcrypt"
path = "modules/Cap.16/Applications/bcrypt.go"
mode = "compile"
hint = """
HINT HERE"""

[[modules]]
name = "cap-16-applications-custom-sort"
path = "modules/Cap.16/Applications/custom-sort.go"
mode = "compile"
hint = """
HINT HERE"""

[[modules]]
name = "cap-16-applications-json-decoder"
path = "modules/Cap.16/Applications/json-decoder.go"
mode = "compile"
hint = """
HINT HERE"""

[[modules]]
name = "cap-16-applications-json-encoder"
path = "modules/Cap.16/Applications/json-encoder.go"
mode = "compile"
hint = """
HINT HERE"""

[[modules]]
name = "cap-16-applications-json-marshal"
path = "modules/Cap.16/Applications/json-marshal.go"
mode = "compile"
hint = """
HINT HERE"""

[[modules]]
name = "cap-16-applications-json-unmarshal"
path = "modules/Cap.16/Applications/json-unmarshal.go"
mode = "compile"
hint = """
HINT HERE"""

[[modules]]
name = "cap-18-concurrence-1"
path = "modules/Cap.18/Concurrence/1.go"
mode = "compile"
hint = """
HINT HERE"""

[[modules]]
name = "cap-18-concurrence-2"
path = "modules/Cap.18/Concurrence/2.go"
mode = "compile"
hint = """
HINT HERE"""

[[modules]]
name = "cap-18-concurrence-3"
path = "modules/Cap.18/Concurrence/3.go"
mode = "compile"
hint = """
HINT HERE"""

[[modules]]
name = "cap-18-concurrence-4"
path = "modules/Cap.18/Concurrence/4.go"
mode = "compile"
hint = """
HINT HERE"""

[[modules]]
name = "cap-19-pkgs"
path = "modules/Cap.19/pkg/main.go"
mode = "compile"
hint = """
HINT HERE"""